version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  app:
    image: achievements-system
    ports:
    - "8080:8080"
    restart: always
    command: ['./wait-for-it.sh', 'db:5432', '--', './main']
    ports:
      - '8080:8080'
    depends_on:
      - db
    links:
      - db
